2020-10-31 05:15:15,781 DEBUG    root            Loaded Command Group: ['gcloud', 'auth']
2020-10-31 05:15:15,783 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application_default']
2020-10-31 05:15:15,932 DEBUG    root            Loaded Command Group: ['gcloud', 'auth', 'application-default', 'print_access_token']
2020-10-31 05:15:15,934 DEBUG    root            Running [gcloud.auth.application-default.print-access-token] with arguments: [--quiet: "True"]
2020-10-31 05:15:15,938 DEBUG    google.auth.transport._http_client Making request: GET http://169.254.169.254
2020-10-31 05:15:18,940 INFO     google.auth.compute_engine._metadata Compute Engine Metadata server unavailable onattempt 1 of 3
2020-10-31 05:15:18,941 DEBUG    google.auth.transport._http_client Making request: GET http://169.254.169.254
2020-10-31 05:15:21,943 INFO     google.auth.compute_engine._metadata Compute Engine Metadata server unavailable onattempt 2 of 3
2020-10-31 05:15:21,944 DEBUG    google.auth.transport._http_client Making request: GET http://169.254.169.254
2020-10-31 05:15:21,944 INFO     google.auth.compute_engine._metadata Compute Engine Metadata server unavailable onattempt 3 of 3
2020-10-31 05:15:21,946 DEBUG    root            Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
Traceback (most recent call last):
  File "/Users/scott/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/surface/auth/application_default/print_access_token.py", line 75, in Run
    creds, _ = google_auth_default.default(
  File "/Users/scott/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/google/auth/_default.py", line 328, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
2020-10-31 05:15:21,959 DEBUG    root            (gcloud.auth.application-default.print-access-token) Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
Traceback (most recent call last):
  File "/Users/scott/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/surface/auth/application_default/print_access_token.py", line 75, in Run
    creds, _ = google_auth_default.default(
  File "/Users/scott/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/third_party/google/auth/_default.py", line 328, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/scott/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/cli.py", line 983, in Execute
    resources = calliope_command.Run(cli=self, args=args)
  File "/Users/scott/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 808, in Run
    resources = command_instance.Run(args)
  File "/Users/scott/Library/Application Support/cloud-code/installer/google-cloud-sdk/lib/surface/auth/application_default/print_access_token.py", line 79, in Run
    raise c_exc.ToolException(six.text_type(e))
googlecloudsdk.calliope.exceptions.ToolException: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
2020-10-31 05:15:21,961 ERROR    root            (gcloud.auth.application-default.print-access-token) Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
